### ISSUE TITLE
REPACK command ?

### ISSUE THREAD

**Issue by foubou** [Ekey/MBTL.BIN.Tool#2]
Ekey, thank you very much for this tool !
I was able to unpack successfully the data000.bin archive.
Do you mind adding a repacker too please ?

**Comment by foubou** [comment]
Hey, I am not sure if you saw my message.
Can you please tell if you are considering working on a repacker one day ? 
Thank you very much ! :)

**Comment by Ekey** [comment]
There is no repacker here, all the information that is needed like offsets, sizes and file names are embedded in main executable.
