### ISSUE TITLE
Unpacker no longer works correctly.

### ISSUE THREAD

**Issue by AyanamiRei1** [Ekey/MBTL.BIN.Tool#3]
Ever since the first release some files are getting extracted without being decrypted.

![image](https://user-images.githubusercontent.com/25233407/149419916-e0a8b077-6680-4d01-9669-4ceb8f879a32.png)

And with the latest update they've added new characters 

If needed I can provide the files from this newest version.

Thanks!

**Comment by w123456789123** [comment]
Can you provide some information? I really need it

**Comment by AyanamiRei1** [comment]
What sort of information?

**Comment by w123456789123** [comment]
最新的mbtl解包工具

**Comment by MaxAkito** [comment]
Same issue, the new character's files also don't seem to appear to be extarcted @Ekey

**Comment by Ekey** [comment]
Unfortunately i don't have game. Can someone upload latest game version to Google Drive? Or maybe someone has an extra key for steam? :B

**Comment by MaxAkito** [comment]
@Ekey Does it need to be a working/cracked version? Or do you just want the bin files.

**Comment by Ekey** [comment]
> @Ekey Does it need to be a working/cracked version? Or do you just want the bin files.

I need full latest game version

**Comment by Mysticus92** [comment]
> 

I can give you a MEGA link.
https://mega.nz/file/8fY2wRKR#JXzaXjQp5gFdRE6v9bBMrbpm-SaZ4RXtijARfMNHfwQ

**Comment by Mysticus92** [comment]
> Unfortunately i don't have game. Can someone upload latest game version to Google Drive? Or maybe someone has an extra key for steam? :B

Here's the MEGA link.
https://mega.nz/file/8fY2wRKR#JXzaXjQp5gFdRE6v9bBMrbpm-SaZ4RXtijARfMNHfwQ

**Comment by Ekey** [comment]
Cache updated to latest game version.
