### ISSUE TITLE
Support for new patch

### ISSUE THREAD

**Issue by MaxAkito** [Ekey/MBTL.BIN.Tool#4]
Two new characters were added, I tried to add them to the cache and figure out it myself but failed.
I've left the update of the game below.

Also, if possible could you detail on how to update the cache? So I can just update the github/build for you.
https://mega.nz/file/k7wiHAwa#nEcrcL0q9XIEeB2wW4b1qQJCLO50EeceCbsYnv4tWAo

**Comment by Ekey** [comment]
Updated
