### ISSUE TITLE
The files in the data folder are not unpacking correctly

### ISSUE THREAD

**Issue by MaxAkito** [Ekey/MBTL.BIN.Tool#5]
Hello, I've ensured I'm running the latest version of the unpacker. Every file that gets translated as a .txt file in the /data directory of unpacked files, comes out as malformed mojibake. Seems like they aren't unpacking correctly.

**Comment by Ekey** [comment]
As I see they have released another [patch 27 April 2022](https://steamdb.info/depot/1372281/history/?changeid=M:8849086400021803518), cache working only with files from this [depot > 14 April 2022](https://steamdb.info/depot/1372281/history/?changeid=M:2533856541277024899). I don't have game to update it again.

**Comment by MaxAkito** [comment]
Latest update
https://mega.nz/file/53pTgIDL#BurWU4gjBEiKSsA2ilbopusZMJlOVQB-GotdZ73sUPA

**Comment by Ekey** [comment]
Updated.
