### ISSUE TITLE
Unpacker stopping at a certain point every time

### ISSUE THREAD

**Issue by Hergog** [Ekey/MBTL.BIN.Tool#8]
Hello there, I wanted to use your unpacker to extract the assets from the updated version of Melty Blood

However no matter what I do the unpacking always stops preemptively before its finished with unpacking all the assets  

Unhandled Exception: System.IO.IOException: I/O error occurred.
   at MBTL.Unpacker.Helpers.ReadBytes(Stream stream, Int32 count)
   at MBTL.Unpacker.BinUnpack.iDoIt(String m_SrcFolder, String m_DstFolder)
   at MBTL.Unpacker.Program.Main(String[] args)

This is what happens every time I use it, the older release didn't have this problem however the DDS files are unviewable if I use an older version of the tool

**Comment by Ekey** [comment]
Hm, it's very weird cuz not so long ago it was updated for the latest version of the game. Are you sure your game updated to latest patch [19 Aug](https://steamdb.info/patchnotes/9347393)? Make sure you are using the latest version of the unpacker from [here](https://github.com/Ekey/MBTL.BIN.Tool/releases)

**Comment by Hergog** [comment]
![issue](https://user-images.githubusercontent.com/78994373/185775485-78f48bbb-f883-4796-b7bb-ca47d266ca91.PNG)
I am indeed using the latest update of the unpacked. And my game is also updated to the newest version with all the added dlc

**Comment by Ekey** [comment]
If you can upload it to GoogleDrive I'll check it out cuz i don't have this game in Steam.

**Comment by Hergog** [comment]
If you mean the Data bins from the latest version. Then here you go

https://drive.google.com/drive/folders/1p5C_87Ya9v_ZBpIIO4Iojaiq5TTeNv4L?usp=sharing

**Comment by Ekey** [comment]
I mean full game.

**Comment by Hergog** [comment]
Well here's the whole game then

https://drive.google.com/file/d/1nozizHo-PlTGUcbJdx1FKi24e5Du-K-6/view?usp=sharing

**Comment by Ekey** [comment]
Updated to [U5](https://github.com/Ekey/MBTL.BIN.Tool/releases)

**Comment by Hergog** [comment]
Just wanted to say thank you. It works just fine now.

**Comment by Buluphont** [comment]
I'm seeing this same issue, even with latest release.  
Possibly because of the two MBTL Game updates that occurred since the last BIN Tool release on 21 Aug?

![unpacking error](https://user-images.githubusercontent.com/12452211/187312292-c1a16ef4-8307-402e-8f09-e89c240615bf.png)
