### ISSUE TITLE
IOException when unpacking latest version

### ISSUE THREAD

**Issue by Buluphont** [Ekey/MBTL.BIN.Tool#9]
I'm seeing the same problem in Issue #8 , even with latest release.  
Possibly because of the two MBTL Game updates that occurred since the last BIN Tool release on 21 Aug?

![unpacking error](https://user-images.githubusercontent.com/12452211/187312292-c1a16ef4-8307-402e-8f09-e89c240615bf.png)

**Comment by Ekey** [comment]
[25 Aug](https://steamdb.info/depot/1372281/history/?changeid=M:5672372077311274103), [26 Aug](https://steamdb.info/depot/1372281/history/?changeid=M:8236421928228568406) there was at least 2 updates

**Comment by zmt00** [comment]
Hi, do you plan on updating this to the latest version? Or should I try downpatching the game?
Thanks.

**Comment by Ekey** [comment]
I don't have a game to make updates.

**Comment by Buluphont** [comment]
That's unfortunate. If you don't mind, how does someone regenerate the cache? I would like to help with a pull request, but I'm not sure where to begin.

**Comment by Ekey** [comment]
To create a new cache, I need a full game. As I said before, I don't have this game in Steam.
You can upload latest game version to Google Drive or Mega? Maybe someone have an extra Steam key for me? :)

**Comment by Buluphont** [comment]
Someone pointed me toward the cache generation tool; opened #10 to close this issue out.
